modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

#credits="" #optional
authors="Ares"

description='''
Kings and Monsters adds bog iron equipment, animated ogres, tribute systems,
patrol escalation, and ogre outposts to Minecraft.
'''

#[[mixins]]
#config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[5.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="bettercombat"
    type="optional"
    versionRange="[3.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[29.0,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[26.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="required"
    versionRange="[15.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="patchouli"
    type="required"
    versionRange="[26.1-94-beta,)"
    ordering="AFTER"
    side="BOTH"

[[mixins]]
    config="kingsandmonsters.mixins.json"
